services:
  coinswap-wa-backend:
    container_name: coinswap-wa-backend
    image: ghcr.io/mactep-mnpl/coinswap-wa-backend:latest
    ports:
      - 8080:8080
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
    depends_on:
      coinswap-wa-database:
        condition: service_healthy
    networks:
      - coinswap-wa-network
    restart: unless-stopped

  coinswap-wa-database:
    container_name: coinswap-wa-database
    image: ghcr.io/mactep-mnpl/coinswap-wa-database:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - coinswap-wa-database:/var/lib/postgresql/data
    networks:
      - coinswap-wa-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  coinswap-wa-network:
    driver: bridge

volumes:
  coinswap-wa-database:
    driver: local 