name: Build and Deploy Containers

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      #- name: Build and push admin-panel
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: ./admin-panel
      #    file: ./admin-panel/Dockerfile
      #    push: true
      #    tags: ${{ env.IMAGE_PREFIX }}/admin-panel:latest

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags:  ghcr.io/mactep-mnpl/coinswap-wa-backend:latest

      #- name: Build and push web-app
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: ./web-app
      #    file: ./web-app/Dockerfile
      #    push: true
      #    tags: ${{ env.IMAGE_PREFIX }}/web-app:latest

      - name: Build and push database
        uses: docker/build-push-action@v5
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: ghcr.io/mactep-mnpl/coinswap-wa-database:latest